# Generated by Django 5.2.1 on 2025-05-13 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
                ('category', models.CharField(choices=[('contract', 'Договор'), ('claim', 'Исковое заявление'), ('act', 'Акт')], max_length=50, verbose_name='Категория')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='documents.client')),
            ],
        ),
    ]
