# Generated by Django 5.2.1 on 2025-06-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'На рассмотрении'), ('approved', 'Утвержден'), ('rejected', 'Отклонен')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
