# Generated by Django 5.2.1 on 2025-06-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шаблона')),
                ('content', models.TextField(verbose_name='Содержимое шаблона')),
                ('category', models.CharField(choices=[('contract', 'Договор'), ('claim', 'Исковое заявление'), ('act', 'Акт'), ('power_of_attorney', 'Доверенность')], max_length=50, verbose_name='Категория')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='client',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='client',
            name='ogrn',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование организации'),
        ),
    ]
