# Generated by Django 5.2.1 on 2025-06-25 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='assigned_clients', to=settings.AUTH_USER_MODEL, verbose_name='Ответственные пользователи'),
        ),
    ]
