# Generated by Django 5.2.1 on 2025-06-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('contract', 'Договор'), ('claim', 'Исковое заявление'), ('act', 'Акт'), ('custom', 'Пользовательский')], default='custom', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
