# Generated by Django 5.2.1 on 2025-06-25 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_document_pdf_file_alter_document_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='pdf_file',
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('contract', 'Договор'), ('claim', 'Исковое заявление'), ('act', 'Акт'), ('custom', 'Пользовательский')], default='custom', max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='document',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='Создан пользователем'),
        ),
        migrations.AlterField(
            model_name='document',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Срок'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Файл документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'На рассмотрении'), ('approved', 'Утвержден'), ('rejected', 'Отклонен')], default='draft', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название документа'),
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название дела')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание дела')),
                ('category', models.CharField(choices=[('litigation', 'Судебное дело'), ('consultation', 'Консультация'), ('contract_review', 'Проверка договора'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Категория дела')),
                ('status', models.CharField(choices=[('open', 'Открыто'), ('in_progress', 'В работе'), ('closed', 'Закрыто')], default='open', max_length=20, verbose_name='Статус дела')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки по делу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('clients', models.ManyToManyField(related_name='cases', to='documents.client', verbose_name='Клиенты')),
                ('documents', models.ManyToManyField(blank=True, related_name='cases', to='documents.document', verbose_name='Документы')),
            ],
        ),
    ]
